#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N DCL_TEST

# Name of stdout output file
#PBS -o job_mpiocl.out

# Total number of nodes and MPI tasks/node requested
# ------     PBS -l select=1:ngpus=1:ncpus=8:host=compute-3-7+select=1:ngpus=1:ncpus=8:host=compute-3-4
#PBS -l select=1:ncpus=4:ngpus=1:vnode=compute-3-4[0]+1:ncpus=4:ngpus=0:vnode=compute-3-4[1]+1:ncpus=4:ngpus=1:vnode=compute-3-7[0]+1:ncpus=4:ngpus=0:vnode=compute-3-7[1]

# Run time (hh:mm:ss) - 1.5 hours
#PBS -l walltime=01:30:00
#----------------------------------------------------------

# Change to submission directory
cd $PBS_O_WORKDIR

cat $PBS_NODEFILE
sort $PBS_NODEFILE | uniq > machines2
cat machines2

export LD_LIBRARY_PATH=/share/apps/AMDAPPSDK-3.0/lib/x86_64/:$LD_LIBRARY_PATH
# Launch MPI-based executable
/opt/ohpc/pub/mpi/mpich-ofi-gnu13-ohpc/3.4.3/bin/mpiexec -np 2 -machinefile machines2 ./profiling.out 
/opt/ohpc/pub/mpi/mpich-ofi-gnu13-ohpc/3.4.3/bin/mpiexec -np 2 -machinefile machines2 ./HIS.out --x 10 --y 10 --z 10 --iterations 10000 --rebalance-interval 1000 
